# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test2 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    var_0 = module_0.quadratic_solver(bool_0, bool_0, bool_0)
    list_0 = [bool_0, bool_0]
    none_type_0 = None
    var_1 = module_0.quadratic_solver(bool_0, bool_0, bool_0)
    module_0.quadratic_solver(list_0, list_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    module_0.quadratic_solver(bool_0, bool_0, bool_0)
