# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test6 as module_0


def test_case_0():
    animal_0 = module_0.Animal()


def test_case_1():
    dog_0 = module_0.Dog()
    var_0 = dog_0.speak()
    assert var_0 == "Woof!"
    animal_0 = module_0.Animal()
    with pytest.raises(NotImplementedError):
        animal_0.speak()


def test_case_2():
    dog_0 = module_0.Dog()
    var_0 = dog_0.speak()
    assert var_0 == "Woof!"
