/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 14:16:51 GMT 2025
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang3.BitField;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class BitField_ESTest extends BitField_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      boolean boolean0 = bitField0.isAllSet(3768);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BitField bitField0 = new BitField((-2968));
      boolean boolean0 = bitField0.isSet((-972));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BitField bitField0 = new BitField(306);
      int int0 = bitField0.setValue(306, 306);
      assertEquals(32, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      int int0 = bitField0.setValue((-1), 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      short short0 = bitField0.setShortValue((byte)0, (short) (-650));
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BitField bitField0 = new BitField(3307);
      short short0 = bitField0.setShortValue((byte)20, (byte)20);
      assertEquals((short)20, short0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BitField bitField0 = new BitField((-2968));
      short short0 = bitField0.setShortBoolean((short)1, true);
      assertEquals((short) (-2967), short0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      short short0 = bitField0.setShort((byte)0);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BitField bitField0 = new BitField(3307);
      short short0 = bitField0.setShort((byte)20);
      assertEquals((short)3327, short0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BitField bitField0 = new BitField(3307);
      byte byte0 = bitField0.setByteBoolean((byte)20, false);
      assertEquals((byte)20, byte0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      byte byte0 = bitField0.setByte((byte)0);
      assertEquals((byte)0, byte0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      byte byte0 = bitField0.setByte((byte)0);
      assertEquals((byte) (-58), byte0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BitField bitField0 = new BitField((-2319));
      int int0 = bitField0.setBoolean((byte) (-15), false);
      assertEquals(2304, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      int int0 = bitField0.set(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      int int0 = bitField0.set(566);
      assertEquals(4086, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BitField bitField0 = new BitField(3307);
      int int0 = bitField0.getValue(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BitField bitField0 = new BitField((-2319));
      int int0 = bitField0.getValue((-1205));
      assertEquals((-3519), int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BitField bitField0 = new BitField(3307);
      short short0 = bitField0.getShortValue((short)0);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      short short0 = bitField0.getShortValue((short) (-1));
      assertEquals((short)2019, short0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BitField bitField0 = new BitField(3307);
      short short0 = bitField0.getShortRawValue((byte) (-1));
      assertEquals((short)3307, short0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BitField bitField0 = new BitField((-2319));
      short short0 = bitField0.getShortRawValue((short) (-178));
      assertEquals((short) (-2496), short0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      int int0 = bitField0.getRawValue((byte) (-40));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BitField bitField0 = new BitField((-717));
      int int0 = bitField0.getRawValue((-2251));
      assertEquals((-2767), int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BitField bitField0 = new BitField((-1025));
      short short0 = bitField0.clearShort((short)1160);
      assertEquals((short)1024, short0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      short short0 = bitField0.clearShort((short) (-1868));
      assertEquals((short) (-1868), short0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      byte byte0 = bitField0.clearByte((byte)0);
      assertEquals((byte)0, byte0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      byte byte0 = bitField0.clearByte((byte) (-94));
      assertEquals((byte) (-94), byte0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      BitField bitField0 = new BitField((-2968));
      int int0 = bitField0.clear((-2968));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      BitField bitField0 = new BitField((-717));
      int int0 = bitField0.clear((-1597));
      assertEquals(192, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      BitField bitField0 = new BitField(3307);
      int int0 = bitField0.clear((-1));
      assertEquals((-3308), int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      int int0 = bitField0.getValue((-1));
      assertEquals(2019, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      int int0 = bitField0.set((-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      int int0 = bitField0.setValue((byte)0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      int int0 = bitField0.getRawValue((short) (-1));
      assertEquals(4038, int0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      BitField bitField0 = new BitField(222);
      byte byte0 = bitField0.setByteBoolean((byte)100, true);
      assertEquals((byte) (-2), byte0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      byte byte0 = bitField0.setByteBoolean((byte)34, false);
      assertEquals((byte)0, byte0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      BitField bitField0 = new BitField(3745);
      short short0 = bitField0.setShortBoolean((short)645, false);
      assertEquals((short)4, short0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      BitField bitField0 = new BitField((-532));
      int int0 = bitField0.setBoolean((-532), true);
      assertEquals((-532), int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      int int0 = bitField0.setBoolean(0, false);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      BitField bitField0 = new BitField(4038);
      boolean boolean0 = bitField0.isAllSet(4038);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      boolean boolean0 = bitField0.isAllSet((byte)34);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      boolean boolean0 = bitField0.isSet((byte)102);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      boolean boolean0 = bitField0.isSet(0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      BitField bitField0 = new BitField(0);
      short short0 = bitField0.setShortBoolean((short)0, true);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      short short0 = bitField0.getShortRawValue((byte)0);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      short short0 = bitField0.setShort((byte)124);
      assertEquals((short) (-4738), short0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      byte byte0 = bitField0.clearByte((byte)124);
      assertEquals((byte)24, byte0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      short short0 = bitField0.getShortValue((short) (-1));
      assertEquals((short) (-2381), short0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      short short0 = bitField0.setShortValue((short)1461, (short) (-1295));
      assertEquals((short) (-6669), short0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      short short0 = bitField0.clearShort((short)0);
      assertEquals((short)0, short0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      BitField bitField0 = new BitField((-4762));
      byte byte0 = bitField0.setByte((byte)34);
      assertEquals((byte)102, byte0);
  }
}
