/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 14:20:18 GMT 2025
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class Add_ESTest extends Add_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Add add0 = new Add();
      int int0 = add0.add(1, 2);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Add add0 = new Add();
      int int0 = add0.add(1, 1);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Add add0 = new Add();
      int int0 = add0.add(0, 2);
      assertEquals(0, int0);
  }
}
