# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import test1 as module_0


def test_case_0():
    bytes_0 = b"6\xc4&\xb2\x8f\xf6y\xf5\x08s\xa0{tdrf"
    with pytest.raises(TypeError):
        module_0.reverse_and_upper(bytes_0)


def test_case_1():
    str_0 = "#HF8("
    var_0 = module_0.reverse_and_upper(str_0)
    assert var_0 == "(8FH#"
    var_1 = module_0.reverse_and_upper(var_0)
    assert var_1 == "#HF8("
    var_2 = module_0.reverse_and_upper(str_0)
    assert var_2 == "(8FH#"
    float_0 = -171.928255
    var_3 = module_0.reverse_and_upper(var_2)
    assert var_3 == "#HF8("
    var_4 = module_0.reverse_and_upper(var_2)
    assert var_4 == "#HF8("
    with pytest.raises(TypeError):
        module_0.reverse_and_upper(float_0)
